### ISSUE TITLE
How to configure WoWSimpleRegistration

### ISSUE THREAD

**Issue by hkbbdx** [mserajnik/vmangos-deploy#2]
Hello!
I'm very sorry to bother you again.
I used WoWSimpleRegistration to register accounts for other players. The website configuration is as follows:
```
    Auth Database DBName
=====================================================================*/
$config['db_auth_host'] = '127.0.0.1';
$config['db_auth_port'] = '3306';
$config['db_auth_user'] = 'mangos';
$config['db_auth_pass'] = 'mangos';
$config['db_auth_dbname'] = 'realmd';
/*===================================================================
Your character's databases.
If your server has a lot of realms you can check the example at the bottom of the file.
=====================================================================*/
$config['realmlists'] = array(
    "1" => array(
        'realmid' => 1, // Realm ID
        'realmname' => "Realm 1", // Realm Name
        'db_host' => "127.0.0.1", // MySQL Host IP
        'db_port' => "3306", // MySQL Host Port
        'db_user' => "mangos", // MySQL username
        'db_pass' => 'mangos', // MySQL password
        'db_name' => "characters" // Characters database name
    )
);
```
Access the website, prompt: Access denied.

How can I change the settings, or can I add a simple registration website?

**Comment by mserajnik** [comment]
In general, please don't open issues asking how to configure other software.

But as a pointer, assuming you are tring to run WoWSimpleRegistration on the same machine:

You'll have to expose your database port to the host machine. You can do this by adding a `ports` section to the `database` service:

```yaml
services:
  database:
    image: ghcr.io/mserajnik/vmangos-database
    restart: unless-stopped
    ports:
      - 3306:3306 # Expose the database port to the host machine

# [...]
```

This will make it so that your database can be accessed outside of Docker.

You'll also have to adjust the configuration of WoWSimpleRegistration to match:

- `$config['db_auth_user']` and `$config['realmlists']['1']['db_user'`] should be `root`
-  `$config['db_auth_pass']` and `$config['realmlists']['1']['db_pass'`] should be `password` (unless you changed it)
- You will probably also have to adjust `$config['realmlists']['1']['realmname']` to match your realm's name (set [here](https://github.com/mserajnik/vmangos-deploy/blob/master/compose.yaml.example#L32C9-L32C31)).

> Access the website, prompt: Access denied.

This sounds a bit like WoWSimpleRegistration might be also otherwise be misconfigured/not running if you can't access it at all, but I can't help you with that.

For further information on how to configure WoWSimpleRegistration, please ask in their issue tracker instead.

**Comment by hkbbdx** [comment]
thank you!
