### ISSUE TITLE
Image for version 4544 seems to contain build for 5875

### ISSUE THREAD

**Issue by orygg** [mserajnik/vmangos-deploy#4]
As stated in the title, ghcr.io/mserajnik/vmangos-server:4544 seems to contain the build for 5875.

Steps to reproduce:

1. Change image tag in default config
2. Copy extracted data from 4544 client to storage/mangosd/extracted-data
3. Start via compose up

=> Error message that it cannot find dbc files in data/5875/dbc

To increase the likelihood that I did not overlook a mistake by myself I

1. copied dbc data to data/5875/dbc, which lead to an error message about the wrong field count in (among others) ItemSet.dbc, consistent with the build being 5875 and not 4544, and
2. greped in the 4544 image for the structure describing strings of ItemSet (see https://github.com/vmangos/core/blob/development/src/game/Database/DBCfmt.h#L53) and found the shorter one, but neither of the longer ones.

**Comment by mserajnik** [comment]
Thank you very much for the report; it appears I forgot to actually pass in the correct client version (see the `-DSUPPORTED_CLIENT_BUILD=5875` [here](https://github.com/mserajnik/vmangos-deploy/actions/runs/8563457093/job/23468522285#step:7:1634)).

I am not quite sure how that happened, because I did test this; however, I did some refactoring in the GitHub Actions workflow configuration before making this repository public and I must've accidentally removed the build argument for the version when shuffling things around (with a force push of the amended initial commit).

https://github.com/mserajnik/vmangos-deploy/commit/8fae814f8ea1938f6d81a30347998b2337516ad2 should fix that.

~~I've manually triggered [a rebuild](https://github.com/mserajnik/vmangos-deploy/actions/runs/8567680410) which should be done in a few hours.~~

__Edit 3:__ Fixed the build issues that occured after this fix (attempting to compile unsupported versions, see [here](https://github.com/vmangos/core/issues/2569#issuecomment-2039402597)) via https://github.com/mserajnik/vmangos-deploy/commit/ca0d11d3ebb76552ce95982e7cdb86395a1a04c8.

**Comment by mserajnik** [comment]
This should now be fixed with the latest images. I also went ahead and deleted all the old images (so no one accidentally tries running one of those and runs into this issue again).

Thanks again for the report, this would've probably gone undetected for quite a while longer since I personally only run a version `1.12.1.5875` server.
