### ISSUE TITLE
No PHPMYADMIN for ARM

### ISSUE THREAD

**Issue by Fantazyoosh** [mserajnik/vmangos-deploy#5]
When starting server with option for PhpMyAdmin i'm getting "phpmyadmin The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested "

I'm on a Raspberry Pi 4. It works great otherwise!

**Comment by mserajnik** [comment]
~~I think I know what's going on; can you please try changing the image of the `phpmyadmin` service to `image: phpmyadmin` (from `image: phpmyadmin/phpmyadmin`) and see if that works? The rest of the configuration can stay the same.~~

__Edit:__ I was able to test and confirm this:

The issue was that I referenced an [old phpMyAdmin image](https://hub.docker.com/r/phpmyadmin/phpmyadmin/) instead of the [new one from the official DockerHub repository](https://hub.docker.com/_/phpmyadmin/) in the example Docker Compose configuration. No `aarch64` variants were provided for the old image which is likely why you got that error. This should be fixed if you adjust the `phpmyadmin` service to use the new image accordingly (see https://github.com/mserajnik/vmangos-deploy/commit/1e82ee3707b71498dd903b9a6038eec40227a29d).

Thanks for the report!

**Comment by Fantazyoosh** [comment]
Thank you, and thanks for getting me into wow private servers and docker. Fun stuff to play with :)
